services:
  db:
    image: pgvector/pgvector:pg15
    container_name: rocathon-pgvector
    environment:
      POSTGRES_DB: rocathon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
